version: '3'

services:
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build: .
    command: chmod +x boot.sh
    command: ./boot.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
      - metabase
